### ISSUE TITLE
Does this repo contain the implementation of SPN

### ISSUE THREAD

**Issue by glhfgg1024** [JingchunCheng/Seg-with-SPN#2]
Hi Dear Authors, 

I've read your paper about this project, and thanks a lot for sharing your code! I have a question: does this repository contain an implementation on SPN? It seems missing, right? Thanks.

**Comment by wasidennis** [comment]
Thanks for your interest. Currently we are working on the IP issue for SPN, and will upload the pre-trained model once the issue is solved.

**Comment by glhfgg1024** [comment]
Hi @wasidennis, thanks a lot for your reply! If possible, do you have a plan to release the source code of SPN? Thanks.

**Comment by wasidennis** [comment]
It would not be my own call, and we will need to discuss it. Will definitely update the code as soon as we know what to do. Thanks!

**Comment by glhfgg1024** [comment]
Got it! Thanks very much!
