### ISSUE TITLE
compatible caffe installation

### ISSUE THREAD

**Issue by amankh** [JingchunCheng/Seg-with-SPN#4]
Hi, 
I am facing the following issue :
Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: pretrained/PN_ResNetF.caffemodel

I guess, its an issue with the caffe installation. I have tried both, the latest build of caffe and the one you used for SegFlow(which I think was based on flownet2) and the issue remains the same. Could you provide some pointers to solve the issue or share the caffe version/build?
Thanks

**Comment by wasidennis** [comment]
This model should work with the official caffe and the flownet version in SegFlow (though not required as flow is not used here).

Could you elaborate your issue more?
